# Numpy #

In [2]:
import numpy as np

In [3]:
lista = [0,1,2,3,4,5]

In [4]:
arreglo = np.array (lista)

In [5]:
print (lista)

[0, 1, 2, 3, 4, 5]


In [6]:
print (arreglo)

[0 1 2 3 4 5]


In [7]:
print (arreglo - 5)

[-5 -4 -3 -2 -1  0]


In [8]:
print (arreglo -2)

[-2 -1  0  1  2  3]


In [9]:
print (arreglo *4)

[ 0  4  8 12 16 20]


In [10]:
print (arreglo **2)

[ 0  1  4  9 16 25]


# 2.1 Creación de arreglos #

__Rango__

In [11]:
arreglo = np.arange(3,20,2)

In [12]:
print (arreglo)

[ 3  5  7  9 11 13 15 17 19]


__Espacio Lineal__

In [13]:
arreglo_2 = np.linspace(10,40,4)

In [14]:
print (arreglo_2)

[10. 20. 30. 40.]


__Matrices de Ceros y Unos__

In [15]:
arreglo_3 = np.zeros ((2,3,4))

*Creó 2 matrices de 3 x 4*

In [16]:
print (arreglo_3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
arreglo_4 = np.ones ((2,3))

In [18]:
print (arreglo_4)

[[1. 1. 1.]
 [1. 1. 1.]]


# 2.2 Shape de los arreglos #

In [19]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [20]:
print (arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
print(arreglo_2d.shape)

(2, 4)


In [22]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])

In [23]:
print(arreglo_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
print(arreglo_2d.shape)

(4, 2)


In [25]:
print(arreglo_2d.size)

8


# 2.3 Funciones que operan sobre arreglos #

In [26]:
un_arreglo = np.array([-100,2,3,17,25,1,95])

In [27]:
print(un_arreglo.min())

-100


In [28]:
print(un_arreglo.max())

95


In [29]:
arreglo_2d = np.arange(9)

In [30]:
print (arreglo_2d)

[0 1 2 3 4 5 6 7 8]


In [31]:
np.random.shuffle(arreglo_2d)

In [32]:
arreglo_2d = arreglo_2d.reshape((3,3))

In [33]:
print (arreglo_2d)

[[2 5 0]
 [6 4 8]
 [1 3 7]]


In [34]:
print(arreglo_2d.max())

8


In [35]:
print(arreglo_2d.max(axis = 0))

[6 5 8]


In [36]:
print(arreglo_2d.max(axis = 1))

[5 8 7]


In [37]:
arreglo_2d = np.arange(9).reshape(3,3)

In [38]:
print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
print(arreglo_2d[1,:])

[3 4 5]


In [40]:
print (arreglo_2d.max())

8


In [41]:
print (arreglo_2d.min())

0


In [42]:
print(np.min(arreglo_2d), arreglo_2d.min())

0 0


In [43]:
print(np.min(un_arreglo), un_arreglo.min())

-100 -100


# Ejercicios #

__Ejercicio 1__

Escribir un arreglo con 100 números equiespaciados del 0 al 9.

In [44]:
comb = np.linspace(0,9,100)

In [45]:
print (comb)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

__Ejercicio 2__

Crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [46]:
comb_2 = np.zeros (20)

In [47]:
print (comb_2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
comb_2 [0:15] = 1

In [49]:
print (comb_2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


__Ejercicio 3__

Crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [50]:
comb_3 = np.zeros (50)

In [51]:
print (comb_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [52]:
comb_3 = np.zeros (50)

for item in range(25):
    comb_3 [item]=item
print (comb_3)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


__Ejercicio 4__

Crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente.

In [53]:
comb_4 = np.zeros ((3,3))

In [54]:
print (comb_4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
comb_4 [0] [1] = 1

In [56]:
comb_4 [1] [1] = 2

In [57]:
comb_4 [2] [1] = 3

In [58]:
print (comb_4)

[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]]


__Ejercicio 5__

Crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos.

In [59]:
comb_5 = np.zeros ((3,3))

In [60]:
comb_5 = np.diag ((1,1,1))

In [61]:
print (comb_5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


__Ejercicio 6__

Crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos.

In [62]:
comb_6 = np.zeros ((100,100))

In [63]:
print (comb_6)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [64]:
lista = np.ones(100)

In [65]:
comb_6 = np.diag (lista)

In [66]:
print (comb_6)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


# Extra #

*__-->__¿Qué __tipo de dato__ está usando NumPy cuando crea los arreglos?* __ARRAY__

Un array es parecido a una lista en Python y de hecho se pueden crear a partir de ellas.
A diferencia de las listas sus elementos no están separados por comas.

El tipo del array es automáticamente establecido como __int32 (enteros de 32 bits).__

En cambio si uno de los valores fuera decimal:

In [67]:
array = np.array([1, 2, 3, 4, 5, 6.1234])
print(array.dtype)

float64


Entonces el tipo ya sería __float64 (flotantes de 64 bits).__

Los arrays no son listas, sino unas estructuras pensadas para almacenar vectores y matrices, que son conscientes en todo momento de su dimensión, forma y tipo.

*__-->__¿Y si queremos __cambiarle el tipo de dato__, por ejemplo a __int__?*

Para cambiar el dtype del objeto de matriz dado, usaremos la __numpy.astype()function__

__Problema:__ Dada una matriz numpy cuyos datos subyacentes son de 'int32'tipo. __Cambia__ el dtype del objeto dado a __'float64'__ (decimal).

In [68]:
arr = np.array([10, 20, 30, 40, 50])

In [69]:
arr

array([10, 20, 30, 40, 50])

In [70]:
print(arr.dtype)

int32


In [71]:
arr = arr.astype('float64')

In [72]:
print(arr)

[10. 20. 30. 40. 50.]


In [73]:
print(arr.dtype)

float64


In [74]:
arr = arr.astype('int')

In [75]:
print(arr.dtype)

int32


*__-->__¿Qué pasa si usamos __astype(bool)?__*

In [76]:
arr = arr.astype('bool')

In [77]:
print(arr)

[ True  True  True  True  True]


In [78]:
print(arr.dtype)

bool
