# Generala #

1. ¿Cuán probable es obtener una generala en la primera tirada?
2. ¿Cuán probable es obtener una generala con dos tiradas?
3. ¿Cuán probable es obtener una generala luego de las tres tiradas?
4. ¿Qué es más problable: obtener una generala con tres tiradas y cinco dados o cuatros tiradas y seis dados?

In [1]:
import numpy as np

1. Crea la función tirar_n_dados. Debe tomar como argumento por defecto n = 5, pero tiene que funcionar correctamente para otros valores de n.

In [2]:
import random

In [3]:
def tirar_n_dados():
    pass

In [4]:
# siendo n el numero de elementos de tu lista(numero de tiradas)
def tirar_n_dados(n = 5):
    result=[]
    for i in range(0,n):
        result.append(random.randint(1, 6))
    return result

tirar_n_dados()

[2, 2, 1, 2, 6]

2. Crea la función es_generala. Esta función toma como entrada los resultados de tirar_n_dados y devuelve True si es generala y False si no lo es.

In [5]:
def es_generala():
    pass

In [6]:
def es_generala(dados = tirar_n_dados()):
    resultado = True
    valor1 = dados[0]
    for dado in dados:
        if (dado != valor1):
            resultado = False
            break
    return resultado

In [7]:
print (es_generala())

False


In [8]:
array_de_prueba = np.array([2,5,5,5,6])
print(es_generala(array_de_prueba))

False


def tirar_n_dados(n = 5):
    for i in range(10000):
        tirada_dados = tirar_n_dados(n = 5)
        if es_generala(tirada_dados):
            print(tirada_dados)
        else:
            print('No es Generala') # Rever

3. Crea una función seleccionar_mayoria que, dada una tirada de n dados, devuelve cuál es la moda de los resultados y con qué frecuencia. Dos consideraciones:  
*Si los n resultados son distintos, es indistinto cuál valor devuelve.  
*Si hay más de un valor posible para devolver - por ejemplo, en la tira [1, 1, 2, 2, 3] -, es indistinto cuál valor elige.  
Tal vez te sirva saber que estas consideraciones se resuelven automáticamente si utilizas algunas herramientas de NumPy, como np.unique(), np.argmax() y alguna más.

In [9]:
def seleccionar_mayoria():
    pass
    return maximo, frecuencia

In [10]:
def seleccionar_mayoria(dados = tirar_n_dados()):
    print (dados)
    (valores, repeticiones) = np.unique(dados, return_counts=True)
    moda = valores[np.argmax(repeticiones)] # Valores en la posición que más se repite
    frecuencia = repeticiones[np.argmax(repeticiones)]
    return moda, frecuencia

In [11]:
seleccionar_mayoria()

[1, 3, 2, 1, 1]


(1, 3)

In [12]:
array_de_prueba = np.array([1,1,1,5,5])
print(seleccionar_mayoria(array_de_prueba))

[1 1 1 5 5]
(1, 3)


4. Crea una función jugar tome como argumentos n_tiradas con argumento por defecto 3 y dados_total con argumento por defecto 5 y que, utilizando las funciones que definiste antes, juegue a la generala. La función debe devolver un arreglo con las n-tiradas realizadas y un índice indicando en qué tirada logró la generala si corresponde (si no logra la generala, debe devolver un valor que indique que no se logró la generala).

In [13]:
def jugar(n_tiradas = 3, dados_total= 5):
    # Numero de dados a tirar inicialmente
    n_dados = dados_total 
    
    # Dados en la mesa inicialmente
    dados_mesa = np.array([]) 
    
    # Donde guardamos las tiradas
    tiradas = np.zeros((3,5), dtype=int) 
    
    # Numero de tirada exitosa, en la que se logra la generala
    # Inicializar en un valor que indique que NO se obtuvo generala.
    # Si luego se obtiene una generala, se modificará
    tirada_exitosa = -1
    
    # Contamos cuantas tiradas hicimos hasta ahora
    contador_tiradas = 0
    
    while (contador_tiradas < n_tiradas) and tirada_exitosa == -1:
        # Tiramos los dados
        dados_nuevos = tirar_n_dados(n_dados)
        
        # Combinamos los dados recien tirados con los que ya estan en la mesa
        todos_dados = np.concatenate((dados_mesa, dados_nuevos)).astype(int)
        
        # Guardamos tirada
        tiradas[contador_tiradas,:] = todos_dados
        
        # Nos fijamos si es generala
        if es_generala(todos_dados):
            # Si es, modificamos el valor de tirada exitosa.
            # Esto debe cortar el loop.
            tirada_exitosa = contador_tiradas + 1
            break
        else:
            # Si no es generala, sigue tirando 
            # Se fija qué dados debe dejar en la mesa
            maximo, frecuencia = seleccionar_mayoria(todos_dados)
            dados_mesa = np.repeat(maximo, frecuencia)
            
            # Calcula cuántos dados volver a tirar
            n_dados = dados_total - len(dados_mesa)
        
        # Suma al contador de tiradas
        contador_tiradas = contador_tiradas + 1
    return tiradas, tirada_exitosa

In [14]:
# TESTEO
for i in range(5):
    tiradas, tirada_exitosa = jugar(3, 5)
    if tirada_exitosa >=0:
        print(tiradas, tirada_exitosa)

[1 6 4 4 6]
[4 4 5 4 3]
[4 4 4 1 4]
[3 1 6 4 3]
[3 3 1 3 5]
[3 3 3 1 1]
[6 1 5 5 4]
[5 5 5 5 1]
[5 5 5 5 3]
[5 1 2 4 4]
[4 4 6 3 5]
[4 4 6 1 2]
[3 6 6 6 6]
[[3 6 6 6 6]
 [6 6 6 6 6]
 [0 0 0 0 0]] 2
