In [1]:
mi_edad = 16
if (mi_edad<=18 and mi_edad>=14):
    print ('Hola')

Hola


In [3]:
mi_edad = 16
if (14 <= mi_edad <=18):
    print ('Hola')

Hola


# Diccionario #

In [20]:
diccionario = {
    'nombre' : 'Alejandra',
    'apellido' : 'Seveso',
    'hermanos' : ['Pablo', 'Juan'],
    'horas' : [
        {
            'hora' : '10hs',
            'temperatura' : '10.5'
        },
        {
            'día' : 'lunes',
            'mes' : 'mayo'
        }
    ]
}

In [10]:
diccionario ['nombre']

'Alejandra'

In [11]:
diccionario ['hermanos'][0]

'Pablo'

In [21]:
diccionario

{'nombre': 'Alejandra',
 'apellido': 'Seveso',
 'hermanos': ['Pablo', 'Juan'],
 'horas': [{'hora': '10hs', 'temperatura': '10.5'},
  {'día': 'lunes', 'mes': 'mayo'}]}

In [22]:
for item in diccionario:
    print(item)

nombre
apellido
hermanos
horas


In [26]:
for item in diccionario.items():
    print(item)

('nombre', 'Alejandra')
('apellido', 'Seveso')
('hermanos', ['Pablo', 'Juan'])
('horas', [{'hora': '10hs', 'temperatura': '10.5'}, {'día': 'lunes', 'mes': 'mayo'}])


In [28]:
for item, valor in diccionario.items():
    print(valor)

Alejandra
Seveso
['Pablo', 'Juan']
[{'hora': '10hs', 'temperatura': '10.5'}, {'día': 'lunes', 'mes': 'mayo'}]


*diccionario.get['nombre'] * Probarrrrrrrrr

# Arreglos y Rango #

In [39]:
import numpy as np

In [43]:
arreglo = np.arange (0,15)

In [44]:
print (arreglo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [45]:
arreglo [2:7] = 25

In [46]:
print (arreglo)

[ 0  1 25 25 25 25 25  7  8  9 10 11 12 13 14]


In [48]:
arreglo = np.arange(100)

In [49]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
escalar = np.arange (1)

In [53]:
escalar

array([0])

In [54]:
arreglo_2 = arreglo.reshape (10,10)

In [55]:
arreglo_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

*El RESHAPE, convirtió el VECTOR en MATRIZ*
*Para hacer al revez, se concatenan todas las filas de la matriz y se la convierte en VECTOR*

In [56]:
arreglo_2[2:5,::2]

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

*Fila / Columba / Cubo*