# Informe Final Carrera
Profundiza y ajusta la resolución de tus proyectos: agrega al menos una fuente de datos o prueba un modelo que hasta el momento no hayas aplicado. Elabora un informe ?nal que describa el proceso de toma de decisiones. Sustenta la razón por la cual usaste las librerías y aplicaste los métodos al dataset. Todos tus hallazgos deberán ser comunicados en función de la problemática y las preguntas que buscabas responder.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

### Dataset I

In [2]:
banksim = pd.read_csv('bs140513_032310.csv')

In [3]:
banksim.shape

(594643, 10)

In [4]:
banksim.head()

step       customer  age gender zipcodeOri       merchant zipMerchant  \
0     0  'C1093826151'  '4'    'M'    '28007'   'M348934600'     '28007'   
1     0   'C352968107'  '2'    'M'    '28007'   'M348934600'     '28007'   
2     0  'C2054744914'  '4'    'F'    '28007'  'M1823072687'     '28007'   
3     0  'C1760612790'  '3'    'M'    '28007'   'M348934600'     '28007'   
4     0   'C757503768'  '5'    'M'    '28007'   'M348934600'     '28007'   

              category  amount  fraud  
0  'es_transportation'    4.55      0  
1  'es_transportation'   39.68      0  
2  'es_transportation'   26.89      0  
3  'es_transportation'   17.25      0  
4  'es_transportation'   35.72      0

In [5]:
banksim.isnull().sum()

step           0
customer       0
age            0
gender         0
zipcodeOri     0
merchant       0
zipMerchant    0
category       0
amount         0
fraud          0
dtype: int64

In [6]:
banksim[['step','age','amount']].describe().round()

step    amount
count  594643.0  594643.0
mean       95.0      38.0
std        51.0     111.0
min         0.0       0.0
25%        52.0      14.0
50%        97.0      27.0
75%       139.0      43.0
max       179.0    8330.0

In [7]:
pd.unique(banksim['customer'])

array(["'C1093826151'", "'C352968107'", "'C2054744914'", ...,
       "'C1014783484'", "'C849065220'", "'C1809646275'"], dtype=object)

In [8]:
print(banksim['customer'].value_counts())

'C1978250683'    265
'C1275518867'    252
'C806399525'     237
'C515668508'     205
'C1338396147'    195
                ... 
'C1156745710'      6
'C1345586046'      6
'C1743702978'      5
'C1809646275'      5
'C1404665203'      5
Name: customer, Length: 4112, dtype: int64


In [9]:
print(banksim['customer'].value_counts().sum())

594643


In [10]:
#sns.countplot(data = banksim, y = 'customer', order = banksim['customer'].value_counts().index, palette='pastel')
#plt.title('Número de Customers')

In [11]:
pd.unique(banksim['step'])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179], d

In [12]:
print(banksim['step'].value_counts())

175    3774
177    3758
152    3746
178    3743
174    3743
       ... 
5      2525
3      2499
2      2462
0      2430
1      2424
Name: step, Length: 180, dtype: int64


In [13]:
print(banksim['step'].value_counts().sum())

594643


In [14]:
pd.unique(banksim['zipcodeOri'])

array(["'28007'"], dtype=object)

In [15]:
print(banksim['zipcodeOri'].value_counts())

'28007'    594643
Name: zipcodeOri, dtype: int64


In [16]:
print(banksim['zipcodeOri'].value_counts().sum())

594643


In [17]:
pd.unique(banksim['zipMerchant'])

array(["'28007'"], dtype=object)

In [18]:
print(banksim['zipMerchant'].value_counts())

'28007'    594643
Name: zipMerchant, dtype: int64


In [19]:
print(banksim['zipMerchant'].value_counts().sum())

594643


In [20]:
pd.unique(banksim['category'])

array(["'es_transportation'", "'es_health'", "'es_otherservices'",
       "'es_food'", "'es_hotelservices'", "'es_barsandrestaurants'",
       "'es_tech'", "'es_sportsandtoys'", "'es_wellnessandbeauty'",
       "'es_hyper'", "'es_fashion'", "'es_home'", "'es_contents'",
       "'es_travel'", "'es_leisure'"], dtype=object)

In [21]:
print(banksim['category'].value_counts())

'es_transportation'        505119
'es_food'                   26254
'es_health'                 16133
'es_wellnessandbeauty'      15086
'es_fashion'                 6454
'es_barsandrestaurants'      6373
'es_hyper'                   6098
'es_sportsandtoys'           4002
'es_tech'                    2370
'es_home'                    1986
'es_hotelservices'           1744
'es_otherservices'            912
'es_contents'                 885
'es_travel'                   728
'es_leisure'                  499
Name: category, dtype: int64


In [22]:
print(banksim['category'].value_counts().sum())

594643


In [23]:
pd.unique(banksim['amount'])

array([  4.55,  39.68,  26.89, ..., 249.18, 224.81, 190.31])

In [24]:
print(banksim['amount'].value_counts())

14.93     146
26.67     146
17.57     145
17.26     143
16.12     143
         ... 
751.43      1
274.43      1
517.95      1
105.02      1
429.60      1
Name: amount, Length: 23767, dtype: int64


In [25]:
print(banksim['amount'].value_counts().sum())

594643


### Dataset II

In [26]:
banksim_ = pd.read_csv('bsNET140513_032310.csv')

In [27]:
banksim_.shape

(594643, 5)

In [28]:
banksim_.head()

Source         Target  Weight            typeTrans  fraud
0  'C1093826151'   'M348934600'    4.55  'es_transportation'      0
1   'C352968107'   'M348934600'   39.68  'es_transportation'      0
2  'C2054744914'  'M1823072687'   26.89  'es_transportation'      0
3  'C1760612790'   'M348934600'   17.25  'es_transportation'      0
4   'C757503768'   'M348934600'   35.72  'es_transportation'      0

In [29]:
banksim_.isnull().sum()

Source       0
Target       0
Weight       0
typeTrans    0
fraud        0
dtype: int64

In [30]:
banksim_[['Weight']].describe().round()

Weight
count  594643.0
mean       38.0
std       111.0
min         0.0
25%        14.0
50%        27.0
75%        43.0
max      8330.0

In [31]:
pd.unique(banksim_['Weight'])

array([  4.55,  39.68,  26.89, ..., 249.18, 224.81, 190.31])

In [32]:
print(banksim_['Weight'].value_counts())

14.93     146
26.67     146
17.57     145
17.26     143
16.12     143
         ... 
751.43      1
274.43      1
517.95      1
105.02      1
429.60      1
Name: Weight, Length: 23767, dtype: int64


In [33]:
print(banksim_['Weight'].value_counts().sum())

594643


In [34]:
pd.unique(banksim_['typeTrans'])

array(["'es_transportation'", "'es_health'", "'es_otherservices'",
       "'es_food'", "'es_hotelservices'", "'es_barsandrestaurants'",
       "'es_tech'", "'es_sportsandtoys'", "'es_wellnessandbeauty'",
       "'es_hyper'", "'es_fashion'", "'es_home'", "'es_contents'",
       "'es_travel'", "'es_leisure'"], dtype=object)

In [35]:
print(banksim_['typeTrans'].value_counts())

'es_transportation'        505119
'es_food'                   26254
'es_health'                 16133
'es_wellnessandbeauty'      15086
'es_fashion'                 6454
'es_barsandrestaurants'      6373
'es_hyper'                   6098
'es_sportsandtoys'           4002
'es_tech'                    2370
'es_home'                    1986
'es_hotelservices'           1744
'es_otherservices'            912
'es_contents'                 885
'es_travel'                   728
'es_leisure'                  499
Name: typeTrans, dtype: int64


In [36]:
print(banksim_['typeTrans'].value_counts().sum())

594643


`category` del Dataset I y `type_Trans` del 2, son las columnas que pueden cruzarse.

In [37]:
banksim_ = banksim_.rename(columns={'typeTrans':'category'})
banksim_

Source         Target  Weight             category  fraud
0       'C1093826151'   'M348934600'    4.55  'es_transportation'      0
1        'C352968107'   'M348934600'   39.68  'es_transportation'      0
2       'C2054744914'  'M1823072687'   26.89  'es_transportation'      0
3       'C1760612790'   'M348934600'   17.25  'es_transportation'      0
4        'C757503768'   'M348934600'   35.72  'es_transportation'      0
...               ...            ...     ...                  ...    ...
594638  'C1753498738'  'M1823072687'   20.53  'es_transportation'      0
594639   'C650108285'  'M1823072687'   50.73  'es_transportation'      0
594640   'C123623130'   'M349281107'   22.44         'es_fashion'      0
594641  'C1499363341'  'M1823072687'   14.46  'es_transportation'      0
594642   'C616528518'  'M1823072687'   26.93  'es_transportation'      0

[594643 rows x 5 columns]

In [39]:
banksim.dtypes

step             int64
customer        object
age             object
gender          object
zipcodeOri      object
merchant        object
zipMerchant     object
category        object
amount         float64
fraud            int64
dtype: object

In [40]:
banksim_.dtypes

Source       object
Target       object
Weight      float64
category     object
fraud         int64
dtype: object

In [42]:
banksim['amount'] = banksim['amount'].astype(int)

In [43]:
banksim_['Weight'] = banksim_['Weight'].astype(int)

In [45]:
#data = pd.merge(banksim, banksim_, on='category')
#data